### ISSUE TITLE
Autocomplete fields in extended search should warn when used incorrectly

### ISSUE THREAD

**Issue by MartinHammarstedt** [spraakbanken/korp-frontend#121]
The fields for prefix, suffix and sense (and possibly more) should give a warning if you don't select anything from the autocomplete list (similar to the warning for the lemgram field).

Currently everything looks fine to the user, but they get no results.

**Comment by majsan** [comment]
Fixed for our attributes: lemgram, dalin-lemgram, sense, saldo, prefix, suffix and fsvlex.
