### ISSUE TITLE
Search using the new compound annotations

### ISSUE THREAD

**Issue by MartinHammarstedt** [spraakbanken/korp-frontend#122]
The old prefix and suffix annotations are going away and are replaced by the new compound analysis (visible in the sidebar). But we can't remove the old ones until searching is possible in the new ones. This feature should be added to the extended search. How it's supposed to look and work needs to be specified first.

**Comment by majsan** [comment]
- Fasa ut prefix och suffix
- SUC2 ska inte ha `complemgram` hidden, samma som alla andra

# `complemgram`

Enkel sökning på lemgram gör just nu:

   `[(lex contains "hus\.\.nn\.1" | prefix contains "hus\.\.nn\.1")]`

ska ändras till:

   `[(lex contains "hus\.\.nn\.1" | complemgram contains "hus\.\.nn\.1+.*")]`

eller för efterled:

   `[(lex contains "hus\.\.nn\.1" | complemgram contains ".*+hus\.\.nn\.1")]`
   
I avancerad söknining ska alternativen förled, efterled, mellanled, innehåller,
inte innehåller finnas för `complemgram`.

# `compwf`

Enkel sökning påverkas ej och i avancerad sökning ska samma alternativ som för
`complemgram` finnas.

**Comment by majsan** [comment]
Done
