### ISSUE TITLE
Chrome 83 new input focus styling

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#137]
Chrome 83 introduced a new input focus styling, that will be used in Korp for at least text inputs and selects.

![image](https://user-images.githubusercontent.com/530762/86225746-f34cd080-bb8a-11ea-9ce4-4eaf3bace370.png)

Restyle this to another look that fits Korp better, while maintaining clarity of what elements are focused.

**Comment by jroxendal** [comment]
These things are usually fixed using some sort of css reset stylesheet, which is being loaded through bootstrap 3: 
https://github.com/spraakbanken/korp-frontend/blob/7e1ee234812c3a8838be2d34086159fd1d347188/app/styles/_bootstrap-custom.scss#L6

Probably some more updated version of normalize solves this issue. I'll have a closer look at some point.

**Comment by jroxendal** [comment]
fixed with tailwind.

**Comment by majsan** [comment]
Does not work for me in Linux.

**Comment by jroxendal** [comment]
Fixed with tailwind ring, for real this time.
