### ISSUE TITLE
Dead links to all of your documentation

### ISSUE THREAD

**Issue by simongray** [spraakbanken/korp-frontend#138]
All 3 [links to documentation](https://github.com/spraakbanken/korp-frontend/blame/dev/README.md#L9-L11) at the top of the `README.md` yield 404 not found messages.

**Comment by jroxendal** [comment]
There's a fix in dev. master has still not been updated, though.

**Comment by simongray** [comment]
Awesome!

**Comment by simongray** [comment]
Closing this now since you've fixed the issue.
