### ISSUE TITLE
Trend diagram table export button does not work in Firefox

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#14]
Pressing the “Export” button in the trend diagram table view seems to have no effect when using Firefox (version 66.0.5 on Linux, reportedly also versions on Windows and Mac). It works correctly in Chrome and reportedly Safari.

This bug affects at least Korp 7.0.0 at Språkbanken and Korp 5.0.10 at the Language Bank of Finland. I haven’t tried if it has been fixed in the development version.

(The bug was first reported by Tommi Jauhiainen of FIN-CLARIN.)

**Comment by majsan** [comment]
This worked for me in Firefox 72, but I made an update anyway based on a Stackoverflow comment in https://stackoverflow.com/questions/3749231/download-file-using-javascript-jquery:

>For it to work on Firefox, do document.body.appendChild(link) before the click and after the click you can do link.remove() to avoid polluting the DOM.
