### ISSUE TITLE
Statistics pie chart animation issues

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#145]
When hovering over a slice in the statistics pie chart it bounces around for a while in an ugly way. Then looks the same as before hover, but it should be bigger so that we can see which slice is active. This seems to happen for every slice except one in each chart.

Also hovering over a slice and then moving the pointer to the slice label makes the slice inactive.

**Comment by arildm** [comment]
Not relevant since we changed chart lib in 20a0ccfd
