### ISSUE TITLE
yarn build fails when modes dir does not contain an HTML file

### ISSUE THREAD

**Issue by simongray** [spraakbanken/korp-frontend#162]
This is the error output you get if you attempt to run `yarn build` without an HTML file in the modes directory using the latest `dev` branch:

```
#9 37.78 LOG from copy-webpack-plugin
#9 37.78 <e> unable to locate 'app/modes/*html' at '/opt/korp-frontend/app/modes/*html'
```

I try to not change the korp-frontend code too much, so my solution is just to create a dummy HTML file as a step in the Dockerfile I use to set up our Korp frontend: 

```dockerfile
RUN touch /opt/korp-frontend/app/modes/glen.html
```

I think the fact that an HTML file is required for the build to run, is probably a bug, right? I don't think we need it in our setup at least.

**Comment by majsan** [comment]
I agree it's a bug. Hopefully really easy to fix in the Webpack configuration.
