### ISSUE TITLE
Loglik comparison broken for "Compile on baseform"

### ISSUE THREAD

**Issue by phildiderichsen** [spraakbanken/korp-frontend#163]
When I do an extended search on "part-of-speech is adjektiv" in "August Strindbergs brev" vs. "August Strindbergs verk" and do a comparison with "compile based on" set to "baseform" (or any other attribute other than "word"), the result will show what appears to be the correct frequency values - but no baseforms. Same result with other corpora. In the console, I see the error "TypeError: i is not a function".

The comparison works correctly if I set "compile based on" to "word".
<img width="1149" alt="Screenshot 2021-03-30 at 15 16 14" src="https://user-images.githubusercontent.com/69901748/112994817-ed603c00-916a-11eb-9bec-cdccd651f4fb.png">

**Comment by majsan** [comment]
Thanks for the bug report! It seems as I have already fixed this, because it works now in `dev`. Will be merged to `master` soon.
