### ISSUE TITLE
Bug in statistics display

### ISSUE THREAD

**Issue by phildiderichsen** [spraakbanken/korp-frontend#164]
When a corpus has a P-attribute configured that does not exist as a 'case' in the reduceStringify function in frontend/app/config/statistics_config.js, selecting it under "sammanställ på:" in the Statistics pane will cause the statistics display to misbehave.

I can reproduce this on https://spraakbanken.gu.se/korp with an awkward search on "före" as "förled" under "sammansatta ordformer" (see picture). Selecting "sammansatta ordformer" under "sammanställ på:" produces no statistics table. Also, I see the error message "jQuery.Deferred exception: r is undefined reduceStringify@https://spraakbanken.gu.se/korp/bundle.js:24:41255".

Complete URL for my search:

https://spraakbanken.gu.se/korp/#?cqp=%5Bcompwf%20starts_with_contains%20%22f%C3%B6re%5C%2B%22%5D&search_tab=1&corpus=abounderrattelser2012&stats_reduce=word,compwf&result_tab=2&search=cqp

The issue can be worked around in a couple of ways.

1. Hardcode the P-attribute as a case in the reduceStringify function in frontend/app/config/statistics_config.js, or
2. Define the stats_stringify function in the configuration of the P-attribute as suggested in the korp-frontend docs, like so:

var lanchart_ttt = { label: "ttt",
    opts: settings.defaultOptions,
    order: 2,
    stats_stringify: function(values) {return values.join(" ")}
    };

However, there ought to be a reasonable default behavior for 'unknown' P-attributes.

<img width="1138" alt="Screenshot 2021-04-13 at 16 10 41" src="https://user-images.githubusercontent.com/69901748/114566872-fd9c0f00-9c72-11eb-9d29-e3ef24fcc912.png">

**Comment by majsan** [comment]
>However, there ought to be a reasonable default behavior for 'unknown' P-attributes.

Fixed in 69cd1e1. Both default behavior for presentation/pretty-printing and the CQP-expression created to show an example KWIC-tab.
