### ISSUE TITLE
Parallel mode: Only word and time interval can be searched

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#167]
The parallel mode does not offer any other attributes for search than the word and time interval, regardless of the language and corpus:

![screenshot_Korp_9_SB_parallel_search_attributes_20210423](https://user-images.githubusercontent.com/22955638/115865637-43aa5d00-a441-11eb-9468-daf21e98ee57.png)

I suppose this is a bug rather than a feature. It would appear to be present in [Korp v9 at Språkbanken](https://spraakbanken.gu.se/korp/?mode=parallel) as of 2021-04-23 and the current head of the `dev` branch (commit 116df39).

I think I tracked the problem down to function `onCorpusChange` in the controller of the `extendedOrBlock` component in `search_controllers.js`:
https://github.com/spraakbanken/korp-frontend/blob/116df39de873fbd8821372be01625cedec6d618d/app/scripts/search_controllers.js#L558-L567

The code sets `ctrl.types` using `settings.corpusListing.getAttributeGroups(lang)`. If I understand correctly, that returns the available attributes for the selected corpora whose configurations have the value of the property `lang` equal to the value of the argument `lang`. However, `lang` is set here to `$rootScope.lang`, which apparently is the Korp user interface language as a two-letter language code, whereas the language codes in the `lang` property of corpus configurations use three-letter language codes. As a result, `settings.corpusListing.getAttributeGroups(lang)` never finds anything, so Korp shows only the attributes word and time interval that are always present.

I think `lang` should get its value from the value of the language drop-down instead, and it should be changed not only when the corpus selections change but also when the language is changed (in function `langChange` in `ParallelSearch` controller in `parallel_mode.js` or somewhere else?). However, I don’t know right away how that should be implemented, so I’d leave it to you who know the code much better, instead of spending time trying to figure it out myself.

(As a side note, I find it a bit complicated that the `ParallelSearch` controller and class `ParallelKwicResults` are defined in `parallel_mode.js`, which is now in a separate configuration repository. At least I consider the parallel search functionality to be an integral part of Korp, so I’m wondering if there are conceptual or technical reasons why that code is not in the main repository, as for example `ParallelCorpusListing` is defined in `util.js`.)

**Comment by majsan** [comment]
I will try to fix this ASAP.

>At least I consider the parallel search functionality to be an integral part of Korp, so I’m wondering if there are conceptual or technical reasons why that code is not in the main repository, as for example ParallelCorpusListing is defined in util.js.

Me too! This is technical debt, from the many years back when the parallell mode was implemented. The code should be moved to the proper repository with only corpus configuration left in `paralell_mode.js`.

Also we have a plan to move the corpus configuration to the backend instead. Not sure how it is going to work yet, but I think it is good for you to know. And of course, before that, the parallell code (and all other code) must be decoupled from the corpus configuration.

I have opened two new issues if there is any further discussion:
https://github.com/spraakbanken/korp-frontend/issues/168
https://github.com/spraakbanken/korp-frontend/issues/169

**Comment by janiemi** [comment]
Thank you for fixing this so quickly. Even though I think the parallel search will be broken until at least #170 is fixed, too, I find this better than the previous state.

Thanks also for the information on the plan to move corpus configurations to the backend. I think that sounds interesting but I suppose it’s a major undertaking. I’d have some comments on the matter that I’ll post to #169, later this week, I hope.
