### ISSUE TITLE
Move code for parallel mode to main repo

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#168]
All the code in https://github.com/spraakbanken/korp-frontend-sb/blob/dev/app/modes/parallel_mode.js must be moved to this repository while the corpus configuration should be left in the modes file.

**Comment by majsan** [comment]
Done!

**Comment by majsan** [comment]
@janiemi Now #170 is fixed and also I have moved all the parallel code to the main repository. A new property for modes has been added (which allows for having multiple parallel modes without having to copy the code):

```
    {
        localekey: "parallel_texts",
        mode: "parallel",
        parallel: true
    },
```

The automated tests work, and I have done our internal test cases (https://github.com/spraakbanken/korp-frontend-sb/blob/dev/test/testcases.md) and also some exploratory testing. I hope that the parallel mode is working as intended again!

**Comment by janiemi** [comment]
@majsan Thank you very much! The parallel mode would now seem to work as I’d expect, and moving code out of the mode file is great, too.

The JavaScript console shows some parallel CQP parsing errors and TypeErrors in certain situations, and the URL hash sometimes seems to contain spurious `cqp_lng` parameters, but I don’t see if or how they affect the functionality, so they are probably cosmetics only. I nevertheless reported them in #173.

**Comment by majsan** [comment]
Thank you for testing and reporting! I have seen the CQP parsing errors too and somewhat ignored them due to the fact that everything seems to work. But they should be fixed at some point.
