### ISSUE TITLE
Extended search (dev): Text input fields lose focus after each key press

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#178]
Text input fields without autocompletion in the extended search lose focus after each key press in the development version (Korp Labs/Korplabbet) as of 2021-08-09 (and commit 1bc5e6aa, head of branch `dev` as of 2021-06-24); the production Korp works fine.

_Edit_: Additional observations: Focus is lost only when the value is modified: e.g. pressing an arrow key does not lose focus. And focus not lost if you type fast enough, but the focus _is_ lost as soon as you pause typing.

(I don’t know if it would be better to report here bugs only in the production Korp (`master`), as `dev` is naturally work in progress, but I think this is a showstopper bug that is also present in your public Korp Labs.)

**Comment by majsan** [comment]
Fortunately an easy fix. And yes, please report bugs as you find them, even if it is in `dev`. I also report all bugs I find, if I don't fix them immediately.

**Comment by janiemi** [comment]
Seems to work; thanks very much for this and the other recent fixes! Now I can again use `dev` as the base for our modifications. And I’ll report bugs in `dev` also in the future.
