### ISSUE TITLE
Autocompletion (dev): Autocompletion list is reset after pressing key down

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#179]
When you press key down in a text input field with autocompletion (in either simple or extended search), the list closes, a spinner appears for a short while and the list reopens, with a possible selection in the same place as before pressing the key. In contrast, key up works as expected.

This happens in the development version (Korp Labs/Korplabbet) as of 2021-08-09 (and commit 1bc5e6aa, head of branch `dev` as of 2021-06-24); the production Korp works fine.

**Comment by majsan** [comment]
This broke in a13149fab when the autoc-component was rewritten. Will fix ASAP.
