### ISSUE TITLE
Statistics: Example KWIC, trend diagram and map do not open for values with a variant suffix

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#181]
If a baseform (or another attribute whose values may have numbered variants) contains a variant suffix (a colon followed by a number(?)), its statistics example KWIC does not open. And if you select such a value in the statistics table and try to get a trend diagram or a map for the value, nothing happens. The JavaScript console shows the error message “bundle.js:24 Uncaught ReferenceError: parts is not defined”.

For example, search
https://spraakbanken.gu.se/korplabb/#?lang=en&cqp=%5B%5D&corpus=sweachum,sweacsam&search_tab=2&stats_reduce=lemma&result_tab=2&search=cqp%7C%5Blemma%20contains%20%22.*:%5B0-9%5D%2B%22%5D
and click “både och” in the statistics table, or tick it and try to get a trend diagram or a map.

Adding `let` or `var` (or maybe `const`) before assigning to `parts` in function `reduceCqp` on line 37 in `statistics_config.js` would seem to fix that:
https://github.com/spraakbanken/korp-frontend/blob/4fed3e49963e4311e6d933fb40cd540f6335a7bf/app/config/statistics_config.js#L36-L38
I thought of creating a pull request for that but maybe you’d like to change that code in other ways, too; please see #182.

**Comment by janiemi** [comment]
I ended up creating pull request #183 for fixing this, as we need the fix anyway. Please feel free to close it without merging if you intend to make bigger changes to the affected code.

**Comment by majsan** [comment]
Thanks! Merged the PR. I don't know when there will be time to make the bigger improvements in `statistics_config.js`, so it's good to get this fixed now.
