### ISSUE TITLE
webpack.common.js: To use path.resolve for jquery or not?

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#186]
If I try to run Språkbanken’s Korp frontend code unmodified, I get the following error when trying to run the dev server with `yarn start`:
```
ERROR in ../korp-frontend-sb-config/app/custom/extended.js
Module not found: Error: Can't resolve 'jquery' in '/home/janiemi/finclarin/korp/git/korp-frontend-sb-config/app/custom'
 @ ../korp-frontend-sb-config/app/custom/extended.js 1:0-17
 @ ./app/scripts/extended.js
 @ ./app/index.js
```

I’ve fixed that by changing in the following code in `webpack.common.js`:
https://github.com/spraakbanken/korp-frontend/blob/4fed3e49963e4311e6d933fb40cd540f6335a7bf/webpack.common.js#L23-L26
the line 26
```javascript
jquery: "jquery/src/jquery",
```
to
```javascript
jquery: path.resolve(__dirname, "node_modules/jquery/src/jquery"),
```

With that single change, the code works for me.

As you have the code as is, I suppose it works for you, so I’m wondering why it doesn’t work for me. Could it be explained by some difference in tooling or the environment? Is one or the other more general or portable?

I’m trying to run the code from branch `dev`, but I came across this issue already last year, so it’s nothing that has changed recently.

**Comment by majsan** [comment]
I install dependencies in the folder where I have checked out our settings repository, we have (had) a package.json with jQuery as the only dependency. This is a much nicer solution, so I have made the change in this repository.

**Comment by janiemi** [comment]
Great; thanks! I had indeed overlooked installing the dependency in the settings repository, but I think it’s better not to have the main repository depend on that.

**Comment by jroxendal** [comment]
I vaguely recall testing having jQuery as peerDependency for the config project, and that it failed. It should be the preferred solutions to this issue, though!

https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by jroxendal** [comment]
That said, if the fix above works, then good :)
