### ISSUE TITLE
Questions: Guidelines or best practices for contributing to Korp?

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#196]
Here are some questions about guidelines or best practices for contributing to Korp, notes on some current practices of mine and maybe also some proposals. They are related mainly to pull requests, Git conventions and coding conventions.

The list is not exhaustive by any means, so I’d be glad to know what else one should take into account when one wishes to contribute to Korp.

I hope that I don’t sound too fussy or opinionated about some matters; please don’t hesitate to disagree or reject anything you don’t like or find worth the trouble. I also apologize for my usual wordiness. And I don’t expect anyone to answer quickly.

## Table of contents

* [Introduction](#introduction)
   * [Background](#background)
   * [Motivation](#motivation)
   * [Applicability](#applicability)
   * [Forum for general matters](#forum-for-general-matters)
* [Pull requests](#pull-requests)
   * [No merge conflicts](#no-merge-conflicts)
   * [Base branch](#base-branch)
   * [Addressing an issue](#addressing-an-issue)
   * [Pull request description](#pull-request-description)
   * [Single or multiple topics](#single-or-multiple-topics)
   * [Squashing commits](#squashing-commits)
   * [Tests](#tests)
* [Git conventions](#git-conventions)
   * [Branch names](#branch-names)
   * [Commit messages](#commit-messages)
   * [Dependencies between repositories](#dependencies-between-repositories)
* [Coding conventions and style](#coding-conventions-and-style)
   * [ECMAScript edition and language features](#ecmascript-edition-and-language-features)
   * [Identifier style](#identifier-style)
   * [File names and directory structure](#file-names-and-directory-structure)
   * [Comments in code](#comments-in-code)
   * [Line length](#line-length)
   * [Semicolons](#semicolons)
   * [Settings](#settings)
* [Documentation](#documentation)

_(Table of contents created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc).)_

### Background

I probably should have asked many of these questions explicitly before creating my first pull request for Korp, instead of writing some of them down as side notes in some issues or pull request descriptions. However, I’ve still got a few small things in progress or in planning that I intend to submit as pull requests, so before doing that, I’d like to get advice or a confirmation on some matters.

### Motivation

I realize that a separate “Contributing Guide” document for Korp might be an overkill as long as there are only a couple of contributors outside Språkbanken and as long as outside contributions are few and far between.

In general, I think that too strict or formal guidelines might raise the bar to contributing but so might no or unclear contributing instructions, which might also lead to more disorder, more work for you and/or fewer contributions accepted. Nevertheless, I think that some guidelines or recommendations _might_ make it easier for others to contribute while also keeping the effort you need to put in handling the contributions as small as possible.

### Applicability

Even though I post this to the Korp frontend repository, I suppose much of this could also be applicable to the [Korp backend](https://github.com/spraakbanken/korp-backend).

### Forum for general matters

I’m wondering if opening an issue in GitHub is the right way to ask questions or start discussions about general matters like this. However, the Korp repositories don’t seem to have [GitHub Discussions](https://docs.github.com/en/discussions) enabled, so issues looked like the only place.

Then to individual questions and notes.

### No merge conflicts

I think a pull request should merge cleanly to the base branch. At least I cannot imagine a situation in which it would make sense to have a pull request with merge conflicts with the base branch.

Of course, you might add new commits to the base branch before merging or perhaps even noticing a pull request, which might result in conflicts. Should it then be the responsibility of the contributor to rebase the pull request onto the new head of the base branch?

### Base branch

I suppose the base branch for a pull request should in general be `dev`. As far as I understand, with the current branching model, it is the branch to which new features and fixes should be added.

I don’t know if a critical bug fix could be based on `master`, but I’d think that such a critical fix should be also merged to `dev` and perhaps back-ported to master.

The base branch might also be a topic branch if you develop a major or experimental feature in a separate branch – such as now the corpus chooser – and if someone would like to contribute to the feature. But would you like that, or would you rather keep such topic branches tightly in your hands?

### Addressing an issue

Should a pull request always address an issue? If I’m planning to implement a feature or fix, or if I’ve already implemented one, should I open an issue for discussing and getting approval of it before creating a pull request? Or would it be fine – or perhaps even better – to discuss it in the pull request itself?

### Pull request description

What information a pull request description should (or should not) contain? I’ve read blog posts describing what a good pull request description should contain; for example:
* https://www.pullrequest.com/blog/writing-a-great-pull-request-description
* https://maddevs.io/blog/how-to-make-a-proper-description-for-a-pull-request/
* https://www.freecodecamp.org/news/how-to-write-a-pull-request-description//

However, I think that at least some of the suggestions might feel rather bureaucratic for the purposes of a project like Korp, at least for small pull requests changing only a few lines of code.

I think that a description suggested on the first of the pages linked above could be enough, adapted to the case as needed: what has been changed, why and how, how it has been and can be tested, and possible other issues.

If you’d like to have pull request descriptions containing certain pieces of information, you could also create a GitHub pull request template.

### Single or multiple topics

Should a pull request address a single topic only (fix or feature)?

Personally, I’d prefer single-topic pull requests in general, but I can imagine cases where commits addressing a couple of related issues could be combined into a single pull request, as I did in #195.

### Squashing commits

Should the commits comprising the changes for a pull request be squashed into a single commit, or is it fine to retain the original commit history? You can also squash the commits at the merge stage if you like (and if you have configured the repository to allow it).

However, would it be easier to see the changes in a single commit than in a possibly long series of commits, some of which might only address typos or omissions in a previous commit? Or what about selectively squashing commits in the pull request branch to get rid of any commits only amending a previous one?

Personally, I like to retain the original commit history and avoid the extra work required for squashing, while at the same time I acknowledge that squashing trivial commits may make the commit history more readable and useful.

Up to now, I have created pull requests originally consisting of one or two commits only, but I might eventually create some from topic branches with a dozen commits or more.

### Tests

I think a pull request should pass tests if the base branch passes. Currently, the base branch doesn’t pass the automated tests, so it’s more difficult to see if a change breaks something.

Should the manual tests listed in [Språkbanken’s test cases](https://github.com/spraakbanken/korp-frontend-sb/blob/dev/test/testcases.md) be performed before making a pull request? Probably only the ones relevant to the pull request would be needed, but it might not always be obvious which ones are relevant and which not. This would require using an installation with Språkbanken’s configuration calling Språkbanken’s backend, but at least I found that easy (once I realized that I can do that).

If the automated tests for Korp were more comprehensive, it might be required or at least strongly recommended that a pull request should be accompanied by tests for the feature or fix it implements. However, widening test coverage would involve a lot of work. Even though adding a test or two as a part of each pull request would work towards more comprehensive tests, requiring that might raise the hurdle for contributing. (At least for me, as I still haven’t acquainted myself with writing tests in the frameworks used in testing Korp.)

As long as the automated tests are rather sparse, should a pull request be accompanied by an appropriate addition or change to the manual tests? A practical difficulty there might be that the document for the manual test cases is in [Språkbanken’s Korp configuration repository](https://github.com/spraakbanken/korp-frontend-sb) instead of this main Korp frontend repository, so you’d need to create a separate pull request for the test.

### Branch names

Would you like to have some naming conventions for branch names for pull requests?

I’ve prefixed the name of a branch fixing issue number _XXX_ with `fix-XXX-`, followed by a short description with dashes between words. For a branch implementing a new feature, I’ve just used a short description. For my private branches, I have used the prefix `f-` for <i>f</i>eature branches, but as that hasn’t been agreed on with you, I have dropped it from the pull request branches to avoid potential confusion. And perhaps `t-` for <i>t</i>opic branches would be more general.

What about dashes or underscores between words, or all-lowercase or mixed-case brach names? Or using slash-separated prefixes as namespaces of some kind? In general, I’ve been using all-lowercase with dashes, except when mentioning a mixed-case or underscored identifier in the branch name. I’ve also used namespace prefixes in some cases in the Korp repositories of the Language Bank of Finland: for example, we currently use [the same repository](https://github.com/CSCfi/Kielipankki-korp-frontend) for the main frontend code and configuration, with configuration branches prefixed with `config/`.

### Commit messages

What about commit message conventions? Descriptive but concise?

I personally have tried to stick to the Git convention of having a relatively short subject line (preferably under 50 characters, but at most 70), followed by a blank line and a more detailed description, except for very simple commits. I’m sometimes rather verbose there, too, for example, mentioning changed files or functions. Is that fine for commits in pull requests, or would you prefer a more concise style?

### Dependencies between repositories

I think it would be good to document somehow if a frontend feature depends on a (recent) backend feature. Should that be done in comments in the code, in the Git commit message, via Git tags, or somehow else? These options are not mutually exclusive, of course.

## Coding conventions and style

I suppose the general advice for coding conventions is “imitate existing code”. However, I’d like to ask (for the confirmation of) your preferences (or the lack of them) on some issues.

### ECMAScript edition and language features

Which ECMAScript edition is the latest one from which features can be used? Or does it depend on the version of Babel? I used to assume ES2015/ES6, but I now noticed that for example rest parameters were introduced only in ES2018.

Are there some language features that should not be used even if in principle supported?

### Identifier style

Should all JavaScript variable and property names use camelCase, or does it matter if I use underscores in, say, local variable names? I’ve understood that camelCase is the custom in JavaScript, but your Korp code also contains underscored names, and I’ve been using them, too.

I suppose identifiers should be descriptive, but do you have any specific wishes?

### File names and directory structure

Do you have any specific file-naming conventions or preferences? The existing names don’t appear completely consistent: for example, [`app/scripts`](https://github.com/spraakbanken/korp-frontend/tree/dev/app/scripts) contains `kwic_download.js`, `pie-widget.js` and `components/readingmode.js`.

Do you have any recommendations as to when a new subdirectory can or should be added?

### Comments in code

What are your preferences for comments in code? Few or many? Terse or verbose? Some particular conventions?

Even though I find Korp code relatively sparsely commented, I have in general tried to comment the code I intend to contribute more extensively than I’d have done otherwise, as I think that might make it easier to you to evaluate if the code is correct and worth merging or not. However, I’m wondering if I’m sometimes too verbose in my comments. An outdated comment is perhaps worse than no comments at all, so it might be better to strive for self-documenting code instead of extensive comments.

### Line length

I noticed that you had increased the line length for auto-formatting JavaScript code from 100 to 120 characters. I’ve still tried to limit lines to 80 characters where possible. Is that fine, or should I run Prettier for my code before submitting a pull request? (Old school, yeah, but I also like to be able to get four editor windows with a font large enough for my eyes side by side on a QHD display.)

I also noticed that Prettier had combined lines to longer ones, where I’d personally have preferred the original multi-line formatting, for example in cases where each item of an array was on a separate line, maybe for simpler modification later (and easier-to-read diffs).

### Semicolons

I suppose the preference is to avoid semicolons to terminate statements in JavaScript where not required.

### Settings

Whenever I’ve added a new configuration setting for a feature, I’ve usually tried to keep the default behaviour the same as before: if you don’t configure otherwise, the new feature is disabled and the new setting shouldn’t affect anything.

Now that the main Korp frontend repository no longer contains `app/config.js`, is [`app/scripts/settings.js`](https://github.com/spraakbanken/korp-frontend/blob/dev/app/scripts/settings.js) the place to set default settings?

If a change requires modifying the configuration, should I also create a pull request containing the appropriate modifications for [Språkbanken’s Korp configuration repository](https://github.com/spraakbanken/korp-frontend-sb/), as I did for #195 (spraakbanken/korp-frontend-sb#7)? Even though I think that in general it would be better to avoid pull requests requiring changes to your configuration, in this particular case I found it justified, as the change was small.

## Documentation

I think that if a new feature or fix in a pull request adds or changes configuration properties or if it otherwise affects Korp installation or development, the changes should also include the corresponding additions or changes to the Korp developer documentation, either [`doc/frontend_devel.md`](https://github.com/spraakbanken/korp-frontend/blob/dev/doc/frontend_devel.md) or maybe in some cases as a separate Markdown document.

**Comment by majsan** [comment]
@janiemi I have added a lot of answers in 4e09015f150. Let me know if you think that there are still questions that must be answered.

**Comment by janiemi** [comment]
@majsan, thank you very much for adding information on contributing to Korp to the development documentation. I think it’s much clearer now if one wishes to contribute to Korp (at least to the frontend).

As far as I can see, you’ve addressed most of my questions at least at some level. However, I didn’t notice answers to the following two:

1. Would you like contributors to follow some naming conventions for pull request branches?
2. Do you have preferences for the content or style of commit messages?

These are minor issues, though, and if you haven’t got any specific preferences or wishes regarding them, they of course need not be added to the documentation.
