### ISSUE TITLE
Menu opens outside of window

### ISSUE THREAD

**Issue by MartinHammarstedt** [spraakbanken/korp-frontend#20]
This applies to the current dev branch.

1. Open the menu in the top right.
2. Close it.
3. Change the size of the browser window.
4. Open the menu again.

Result: Menu is positioned outside of the browser window.

**Comment by majsan** [comment]
This only happens in Firefox for me.

Possible fix is to reimplement the "popper" directive using Popper.js (https://popper.js.org/) instead of jQuery UI.
