### ISSUE TITLE
Select first match in KWIC after every search

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#201]
For a search in Korp from the initial state, the first match in the KWIC is selected and its information shown in sidebar. See:

https://spraakbanken.gu.se/korp/?mode=kubord#?cqp=%5B%5D&corpus=kubfreq-gp-2018&page=0&search=word%7Ckatt

This is the expected behavior. However, when doing another search, lets say, for "hund", the first match in the new search is not selected. Additionally, the sidebar is still open, even though no word is selected, and show information about the first match from the previous search.

**Comment by mmatthiesencsc** [comment]
Jyrki and I just reproduced this bug. It does lead to confusion on the users end, especially if searches are from the same corpus with similar search words.

**Comment by janiemi** [comment]
I think I found a simple fix for this bug. I’ll submit a pull request shortly.

I also think that the sidebar should be hidden when the result is empty or an error has occurred, instead of showing information on the previously selected word. My pull request will also address this sub-issue.
