### ISSUE TITLE
Extended search: StructService attribute value selection lists empty before reload

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#202]
In the extended search, attribute value selection lists with `structServiceSelect` initially come up as empty:

![screenshot_Korp_9_SB_extended_selection_empty_20211115](https://user-images.githubusercontent.com/22955638/141772554-0acbf194-7222-465c-87e0-7b3f85bfc5ae.png)

The console shows the following error message (from a local installation of Språkbanken’s `dev` code):

    bundle.js:50448 TypeError: Cannot read properties of null (reading 'tokenValue')
        at reloadValues (bundle.js:10696)
        at bundle.js:10691
        at Scope.$broadcast (bundle.js:54601)
        at bundle.js:22557
        at Scope.$eval (bundle.js:54274)
        at Scope.$apply (bundle.js:54373)
        at ./app/scripts/util.js.window.safeApply (bundle.js:22097)
        at HTMLDivElement.<anonymous> (bundle.js:22556)
        at HTMLDivElement.dispatch (bundle.js:95349)
        at HTMLDivElement../node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js.$event.dispatch (bundle.js:140250)

After reloading the page, the backend `/struct_service` is called (twice with the same parameters, it seems) and the selection list is filled.

However, if you change the attribute and then re-select the attribute with a `structServiceSelect` selection list, the list is again empty. And if you add an _or_ or _and_ condition with the same attribute, the selection lists of the new instances are empty:

![screenshot_Korp_9_SB_extended_selection_empty_or_20211115](https://user-images.githubusercontent.com/22955638/141772591-1ef5940d-09a5-4c57-9156-ec2cc8624a2e.png)

A similar issue happens with `structServiceAutocomplete`: no selection list appears before a reload, and when changing the attribute back and forth, the list does not appear again before a reload.

This happens in both the current production Korp and Korplabbet as of 2021-11-15, as well as in a local installation using Språkbanken’s frontend and configuration from the `dev` branch. I think this worked at least sometime this September.

**Comment by janiemi** [comment]
Based on bisecting, it appears that the bug was introduced in commit 86669666. (I’m sorry I probably didn’t test the fix at the time.)

As far as I can see, it’s a matter of not calling [`reloadValues`](https://github.com/spraakbanken/korp-frontend/blob/09eb5c8745701ee8cbd092432a31462e8aec86f5/app/scripts/extended.js#L41) directly in the function of `selectController` in `extended.js` to set the values initially. (I’m sorry if I use incorrect terminology for AngularJS.) I’ll submit a pull request.

**Comment by majsan** [comment]
Thanks! I was a bit confused first, and thought it was still not working. Turns out our backend was just slow, so I opened https://github.com/spraakbanken/korp-frontend/issues/213
