### ISSUE TITLE
Map: If several places have the same name, only one of them is shown

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#205]
If multiple places have exactly the same name but different coordinates in the value of a `geo` attribute, the map shows a marker only for one of the locations. It seems that the location name is used as a key (object property name), so the last location with the same name overrides preceding ones.

I suppose it is not the intention that only one of the places is shown on the map. Even though it might often be desirable to distinguish the names of different locations somehow, such as with a suffix to the name (for example, _Cambridge, UK_ vs. _Cambridge, Massachusetts_ vs. [some other Cambridge](https://en.wikipedia.org/wiki/Cambridge_(disambiguation))), that might not always be possible or practical. (There also seem to be [several different places named Stockholm](https://sv.wikipedia.org/wiki/Stockholm_(olika_betydelser)), for example, in at least Sweden, Finland and the US, although I think mentions of any of the other Stockholms except the capital of Sweden would be relatively rare.)

This might not be an problem in Språkbanken’s corpora, but we came across the issue in a corpus collection of the Language Bank of Finland.

I will submit a pull request to fix this.

**Comment by majsan** [comment]
Not the intention! Thanks for the fix.
