### ISSUE TITLE
Extended: Memoize attribute values retrieved with structService

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#208]
When the user chooses in the extended search an attribute whose values come from `structService.getStructValues`, the values are re-retrieved from the backend each time the attribute is chosen. This also results in a short delay before a selection list appears for the attribute. And even though the backend caches the result, only one backend call would be necessary for each combination of attribute and corpora.

I think it would be quite easy to memoize the attribute values using `_.memoize`, based on the attribute name and selected corpora. I’ll see if I can implement that myself, and if I succeed, I’ll submit a pull request.

**Comment by majsan** [comment]
Thanks!
