### ISSUE TITLE
POST requests with Angular $http broken

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#218]
POST requests with Angular's `$http` service needs to be treated a bit differently, otherwise the data is sent as JSON and not "form data".

**Comment by janiemi** [comment]
Ok, thanks for fixing the issue. I’m sorry I didn’t test the POST implementation enough to notice this (and I’m no AngularJS expert).

**Comment by majsan** [comment]
The bug was present before your latest PR, so no worries. 

It would affect other services, but I haven't looked enough yet. Reopening just so that I remember to check.
