### ISSUE TITLE
Issue with Sort within corpora: matched word(s)

### ISSUE THREAD

**Issue by phildiderichsen** [spraakbanken/korp-frontend#224]
Språkbanken's Korp works correctly when sorting on matched word(s) within corpora, e.g.:

https://spraakbanken.gu.se/korp/#?cqp=%5Bpos%20%3D%20%22IN%22%5D&corpus=strindbergbrev&search_tab=1&sort=keyword&lang=en&search=cqp

However, we are seeing weird behaviour.

When two corpora are selected, the sort URL param is correctly set to "keyword", but the sort isn't executed.

<img width="1209" alt="Screenshot 2022-01-31 at 11 21 02" src="https://user-images.githubusercontent.com/69901748/151776609-5f1cead7-921f-46d8-aec6-6bf116b41161.png">

When only one corpus is selected, we get the dead bird.

<img width="1209" alt="Screenshot 2022-01-31 at 11 23 31" src="https://user-images.githubusercontent.com/69901748/151776918-6c245ed7-c94d-4b4f-9341-e553101232e7.png">

**Comment by majsan** [comment]
With case number one, two corpora, check the backend call to `/query`. Is the `sort`-parameter sent to the backend? If it is, something is wrong in the backend, otherwise it must be the frontend.

And for the dead bird scenario, same as above, but also, what error does the backend report?

**Comment by phildiderichsen** [comment]
This was due to a missing dependency in the backend. Installing gawk on the backend server fixed the problem. Thanks for helping out, @majsan :)
