### ISSUE TITLE
Tag box improvement

### ISSUE THREAD

**Issue by phildiderichsen** [spraakbanken/korp-frontend#232]
If I'm not mistaken, the tag box as well as within dropdowns are both controlled by the same within parameter, e.g.

var spWithin = {
    "sentence": "sentence",
    "paragraph": "paragraph"
};

A nice little improvement would be to decouple the two dropdown specifications. See, when "within" is "paragraph", it is not relevant (or possible) to search across "paragraph" boundaries. The logical thing for the tag box would be to default to the next structural level down, in this case "sentence". "Paragraph" really shouldn't even be an option. (Hm, but "2 paragraph" should still default to "paragraph" in the tag box. Maybe not the easiest thing to find an automatic solution for). Also, when "within" is "sentence", and there are no structure levels further down, the tag box becomes entirely irrelevant - except if there is a "n sentence" option specified for "within" ...

Anyway, as it is now, a specification of one or more boundaries using tag boxes always also requires changing the "within" value since the two will initially be the same. Would be nice if only one choice was necessary.

<img width="631" alt="Dropdowns" src="https://user-images.githubusercontent.com/69901748/155947991-6ef37551-c5de-4c84-9038-3cc6ec9888d5.png">

**Comment by phildiderichsen** [comment]
Oops, I forgot the use case where one wants to search to or from a boundary, not across it. That completely invalidates my suggestion.

**Comment by majsan** [comment]
Although Korp could tell the user that there can be no tokens before start of the selected within, right?

**Comment by majsan** [comment]
Borrowed your screenshot and created a new issue https://github.com/spraakbanken/korp-frontend/issues/233
