### ISSUE TITLE
What is the right repository for the `dateInterval` extended component?

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#255]
Does the [`dateInterval` extended component](https://github.com/spraakbanken/korp-frontend-sb/blob/2eddbc0518400489200043db46e33b29cb2c0850/app/custom/extended.js#L100-L221) contain something so specific to Språkbanken that makes the [korp-frontend-sb repo](https://github.com/spraakbanken/korp-frontend-sb/) the right place for it, instead of this main korp-frontend repo? At least I haven’t noticed anything such. And if it contains something Språkbanken-specific, could it perhaps be parametrized somehow?

As we also wish to use the `dateInterval` component, at present, we need to copy it to our configuration (as we have done). It also means that your possible improvements or fixes to the component might go unnoticed for some time, and when noticed, we’d need to copy the component again, meaning that the change would appear to have been done by us. (I’d mention the source in the commit message, though.) In contrast, if `dateInterval` were in the main korp-frontend repo, we’d get updates in the same way as for other code, and the Git commit author information would be correct.

**Comment by majsan** [comment]
You're right, it is not that specific. And especially since you are also using it, it should be moved!
