### ISSUE TITLE
Development documentation: Update for YAML configuration

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#263]
The [development documentation](https://github.com/spraakbanken/korp-frontend/blob/211bf5c38f84b38960812350f7f4e7ba245a1962/doc/frontend_devel.md) is now rather outdated in the `dev` branch, as it describes the old JavaScript configuration instead of the new YAML-based one and as it includes corpus configuration that has been moved to the backend.

I appreciate it that you’re probably working on the actual code and you’ll update the documentation later when the code is stabler – or at least that’s what I tend to do. However, the outdated documentation makes it more difficult for me to create pull requests that would add configuration settings that I’d like to do document properly in the new format. It would thus be great to have at least somewhat updated documentation, so that I could see the format in which you prefer to document configuration settings.

Is the YAML representation for corpus configurations to be documented in the backend repository? At least I’d find that logical.

**Comment by majsan** [comment]
I will start working on this probably next week. We don't know yet exactly what will move to the backend configuration, but probably some of the frontend documentation.

**Comment by janiemi** [comment]
Great, thanks!

**Comment by janiemi** [comment]
Looks good; thanks!
