### ISSUE TITLE
Pagination stops working after switching between reading modes

### ISSUE THREAD

**Issue by atlijas** [spraakbanken/korp-frontend#277]
With the search results visible, when one clicks `Show context` and then `Show KWIC`, the pagination breaks. These lines in `korp-frontend/app/scripts/result_controllers.js` seem to be the culprit:

```
if (s.reading_mode) {
    $location.search("reading_mode", "")
} else {
    $location.search("reading_mode")
}
```
With these lines removed, the pagination works, but doing so might break something I'm note aware of. While debugging this, it might be helpful to look at the URL, which changes to `https://spraakbanken.gu.se/korp/#?reading_mode` after clicking `Show KWIC`.

**Comment by majsan** [comment]
This seems to be fixed already on both master and dev.
