### ISSUE TITLE
Statistics example KWIC: Multi-token match shown as multiple single-token matches if statistics compiled on text attributes only

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#289]
When a query matches multiple tokens and statistics are compiled on one or more text (structural) attributes only (not word (positional) ones), a statistics example KWIC shows a separate match for each token of the original query.

For example: [Search “vara säker att” and compile statistics on subject](https://spraakbanken.gu.se/korp/#?corpus=sweachum,sweacsam&cqp=%5Blemma%20contains%20%22vara%22%5D%20%5Blemma%20contains%20%22s%C3%A4ker%22%5D%20%5Bword%20%3D%20%22att%22%5D&search_tab=1&stats_reduce=text_subject&lang=eng&search=cqp&result_tab=2), choose the Statistics tab and click on the value of the subject, for example “Sociologi” with 4 matches, and the example KWIC shows 12 matches, one for each token in the original search result. The example KWIC is returned by [this backend query](https://ws.spraakbanken.gu.se/ws/korp/v8/query?default_context=1+sentence&show=sentence%2Clemma%2Cpos%2Cmsd%2Clex%2Cdephead%2Cdeprel%2Cref%2Csense%2Ccomplemgram%2Cne_ex%2Cne_name%2Cne_type%2Cne_subtype%2Ccompwf%2Cprefix%2Csuffix&show_struct=text_type%2Ctext_subject&start=0&end=24&corpus=SWEACSAM%2CSWEACHUM&cqp=%5Blemma+contains+%22vara%22%5D+%5Blemma+contains+%22s%C3%A4ker%22%5D+%5Bword+%3D+%22att%22%5D&cqp2=%28%5B_.text_subject%3D%22Sociologi%22%5D%29&expand_prequeries=false&incremental=false&context=&default_within=sentence&within=) where I think the relevant parameters are the following:
  - `cqp`: `[lemma contains "vara"] [lemma contains "säker"] [word = "att"]`
  - `cqp2`: `([_.text_subject="Sociologi"])`
  - `expand_prequeries`: `false`

The secondary CQP expression `cqp2` matches separately each token matched by the primary CQP expression. 

I think this issue is somewhat similar to #288, even though the secondary CQP expression is not padded with `[]`’s. I’d thus think that similar solutions would work:

1. Instead of using a secondary CQP expression, add the expression selecting the statistics value(s) with `&` to the last token of the primary CQP (or to the first token if that is faster): `[lemma contains "vara"] [lemma contains "säker"] [word = "att" & _.text_subject="Sociologi"]`.
   In fact, a similar approach seems to be already used if statistics are compiled by both a word and a text attribute, when the secondary CQP can be for example `([word="är" & _.text_subject="Sociologi"] [word="säkert"] [word="att"])`. (A difference is probably that this secondary CQP is not a modification of the primary one.)
2. Instead of using a secondary CQP expression, add the time expression to the primary CQP as a global constraint referring to the `match` label: `[lemma contains "vara"] [lemma contains "säker"] [word = "att"] :: match.text_subject="Sociologi"`
3. Use the `subset` operation in the secondary CQP expression: `subset Last where match: [_.text_subject="Sociologi"]`

My disclaimers and notes in #288 also apply here: I don’t know which of the queries would be the fastest. I think option 3 might be the easiest from the point of view of the frontend, as it wouldn’t need to modify existing CQP expressions. However, the backend would need to be modified not to add a `within` clause to such CQP expressions. And I don’t know if supporting CQP queries of this kind would have some security implications. In options 1 and 2, I think it might be possible to modify the CQP expression with a regular expression replacement operation, without having to parse the CQP, but you’d need to take into account the possible existing global constraint (in the advanced search).

**Comment by majsan** [comment]
Thanks for the bug report. Again, I'll let Martin have a say before trying to fix it.

@MartinHammarstedt Please look at this one, similar to #288 .

**Comment by arildm** [comment]
Fixed in c5316565
