### ISSUE TITLE
getTimeData - add def.resolve()

### ISSUE THREAD

**Issue by starkadur** [spraakbanken/korp-frontend#295]
I have no database defined in config.js in the backend which resulted in an error in the function getTimeData in service.js (in the frontend). I replaced 
`console.error(error)`
 with 
`def.resolve([[], []]) `

so now it looks like this (as it used to do some months before):

getTimeData() {'
                const def = this.timeDefRef
                timeProxy
                    .makeRequest()
                    .fail((error) => {
                        def.resolve([[], []])
                        //console.error(error)
                    })
                    .done(function (...args) {
                    ...

This resolved my error.

**Comment by majsan** [comment]
I will look at it. Maybe there should be an option to not send the request at all.

**Comment by majsan** [comment]
In the future, use `has_timedata: false` in `config.yml`.
