### ISSUE TITLE
Statistics table not shown when compiling on sense with value “|”

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#297]
In Språkbanken’s Korp, when you [search for “säker” and compile statistics based on sense](https://spraakbanken.gu.se/korp/#?corpus=sweachum,sweacsam&cqp=%5Blemma%20contains%20%22s%C3%A4ker%22%5D&search_tab=1&stats_reduce=sense&result_tab=2&search=cqp), only the header row of the statistics table is shown and the JavaScript console shows the error “jQuery.Deferred exception: r is null util.saldoToString@https\://spraakbanken.gu.se/korp/bundle.js:280:27532”.

I looked at it in a local development instance of Språkbanken’s Korp (branch `refactor`) and found that the original error and its location are “TypeError: match is null saldoToString util.js:186”. This seems to happen when one of the values of the `sense` attribute is `"|"`, which is not matched by `util.saldoRegExp`:
https://github.com/spraakbanken/korp-frontend/blob/41782c320ee7b46439dc7a9159f5d9f66eabda5c/app/scripts/util.js#L182-L190

**Comment by janiemi** [comment]
I began to wonder if `util.saldoToString` (or the equivalent functionality) could be moved to the custom code of the frontend configuration, as I think it’s quite specific to the values of the `sense` attribute in Språkbanken’s corpora.

And could `sense` have other values than “|” not matched by `util.saldoRegExp`?

**Comment by majsan** [comment]
I haven't looked much at the original issue, but I agree with you, the Saldo-stuff is very Språkbanken-specific.

**Comment by majsan** [comment]
This was due to the backend sending `"|"` for the sense-attribute when using the parameter `top`, but we changed it to `""`, so now your example works again.

Regarding the other stuff, we will not do anything right now, but we are aware :)
