### ISSUE TITLE
Word links in parallel corpora don't work

### ISSUE THREAD

**Issue by MartinHammarstedt** [spraakbanken/korp-frontend#30]
When selecting a word in the KWIC for parallel corpora with word linking, the corresponding word(s) in the other language should be highlighted. This has stopped working.

[Example](https://spraakbanken.gu.se/korp/?mode=parallel#?lang=sv&stats_reduce=word&parallel_corpora=swe&cqp_swe=%5Bword%20%3D%20%22katt%22%5D&cqp_null=%5B%5D&corpus=saltnld-sv&search=cqp%7C%5Bword%20%3D%20%22katt%22%5D&page=0)

**Comment by majsan** [comment]
Seems to work already
