### ISSUE TITLE
Make long corpus/folder names look better in corpus chooser

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#306]
![image](https://user-images.githubusercontent.com/530762/223126855-5c561ddc-f446-4eb1-add6-5baa71e5f292.png)

Instead of

![image](https://user-images.githubusercontent.com/530762/223126891-e1fef0c2-d69d-4e41-80ca-e0f3818740f0.png)

**Comment by janiemi** [comment]
This would be nice. We’d also like to see the same improvement for corpus _folder_ names: I don’t know if you have folder names that would require two lines but we do have.

**Comment by majsan** [comment]
![image](https://user-images.githubusercontent.com/530762/226835257-b288c8c6-7644-44e1-b927-70749c1c28c4.png)
There is also an issue where the button blocks the name sometimes.
