### ISSUE TITLE
Lemgram and sense links in sidebar only work once

### ISSUE THREAD

**Issue by MartinHammarstedt** [spraakbanken/korp-frontend#32]
1. Perform a search.
2. Click on a lemgram or sense in the sidebar to search for it.
3. Try clicking on another lemgram or sense.

Result: Nothing happens.

**Comment by majsan** [comment]
It only works after having done a search from simple or advanced. Clicking on a lemgram or sense will do an extended search (but the search parameters are not visible in the GUI) and after that it is broken until a new search is done in simple/advanced.

**Comment by majsan** [comment]
Believe it or not, but this is fixed now! Only in `dev`/Korplabb currently.
