### ISSUE TITLE
Parallell mode: linked sentences not aligned correctly in KWIC

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#323]
The linked sentences are always aligned to the left.

**Comment by arildm** [comment]
The closing fix adds `text-align: center`, which is probably better then the left-alignment that was before. But I just found that there is some code in [kwic.js](https://github.com/spraakbanken/korp-frontend/blob/663a33b0f7d28ed939624e9c1b24d69ca5440dae/app/scripts/components/kwic.js#L557), originally added in e51788d, which should compute more specific positions. I'm reopening this now, hoping to restore the effect of that code.
