### ISSUE TITLE
`settings["cqp_prio"]` default contains `grundform` and `lemgram`, which are not names of positional attributes

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#324]
The default value for the `settings["cqp_prio"]` setting in [settings.js](https://github.com/spraakbanken/korp-frontend/blob/7882bcb6636e9183cfea2f16e19de5ec23d4c912/app/scripts/settings.js#L23) contains `"grundform"` and `"lemgram"`, which are _not_ names of positional attributes like the other values, so I suspect that is not as intended.

We saw a noticeable performance improvement in CQP queries such as `[msd = ".*Y.*" & lemma = "X"]` after replacing `grundform` and `lemgram` with the corresponding attribute names `lemma` and `lex` in our own configuration. It appears that before the change, `lemma` and `lex` were treated as less specific attributes than any listed in `settings["cqp_prio"]`, so subexpressions referring to them were moved last in a CQP expression with multiple conjuncts.

It would seem to me that you don’t override the default in the Korp of Språkbanken Text, either, as `msd` seems to be moved before `lemma` in queries such as [this (a bit contrived) example](https://spraakbanken.gu.se/korplabb/#?cqp=%5Bmsd%20_%3D%20%22%5C.NEU%5C.%22%20%26%20lemma%20contains%20%22valfri%22%5D&corpus=sweachum,sweacsam&search_tab=1). The same seems to happen even in the advanced search. In the backend, the query [`[msd = ".*\.NEU\..*" & lemma contains "valfri"]`](https://ws.spraakbanken.gu.se/ws/korp/v8/query?default_context=1%20sentence&show=sentence%2Clemma%2Cpos%2Cmsd%2Clex%2Cdephead%2Cdeprel%2Cref%2Csense%2Ccomplemgram%2Cne_ex%2Cne_name%2Cne_type%2Cne_subtype%2Ccompwf%2Cprefix%2Csuffix&show_struct=text_type%2Ctext_subject&start=0&end=24&corpus=SWEACHUM%2CSWEACSAM&cqp=%5Bmsd%20%3D%20%22.*\.NEU\..*%22%20%26%20lemma%20contains%20%22valfri%22%5D&query_data=&context=&incremental=true&default_within=sentence&within=&cache=false) took 4.7…4.9 seconds, whereas with the order reversed, [`[lemma contains "valfri" & msd = ".*\.NEU\..*"]`](https://ws.spraakbanken.gu.se/ws/korp/v8/query?default_context=1%20sentence&show=sentence%2Clemma%2Cpos%2Cmsd%2Clex%2Cdephead%2Cdeprel%2Cref%2Csense%2Ccomplemgram%2Cne_ex%2Cne_name%2Cne_type%2Cne_subtype%2Ccompwf%2Cprefix%2Csuffix&show_struct=text_type%2Ctext_subject&start=0&end=24&corpus=SWEACHUM%2CSWEACSAM&cqp=%5Blemma%20contains%20%22valfri%22%20%26%20msd%20%3D%20%22.*\.NEU\..*%22%5D&query_data=&context=&incremental=true&default_within=sentence&within=&cache=false) took 1.1…1.2 seconds (after the first search, with `cache=false`).

I did’t create a pull request, as I thought you might wish to change the default `settings["cqp_prio"]` in other ways, too.

**Comment by majsan** [comment]
Good find! I chose to simply change the attribute names to the correct ones for now.
