### ISSUE TITLE
Time interval: simple input does not work

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#377]
If I input years or dates in the _Simple_ input fields of the time interval selector, they are not reflected in the dates shown in the _Advanced_ buttons nor in `cqp` parameter, so in effect, only the _Advanced_ input seems to work (which I find a bit tedious). I think the _Simple_ input _has_ worked at some point.

Screenshot:
![screenshot_Korp_SBX_time_interval_simple_20240711](https://github.com/spraakbanken/korp-frontend/assets/22955638/358d6812-051d-4447-a6a6-e22e62bedaf3)

**Comment by arildm** [comment]
Thanks! Looks like I failed to test the simple input when converting the advanced datetime picker to a component in 587679a35d3ce5f5622034cc161df8f02f0dc1a5.

While fixing this, I also found that the conversion of simple to advanced input was incomplete, so I then also fixed that in bc7fe43d
