### ISSUE TITLE
Simplify time interval CQP covering whole days

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-frontend#379]
The CQP expression generated for a time interval always contains tests for `text_timefrom` and `text_timeto`, even if they are `000000` and `235959`, that is, the user specified only dates. For example, for the year interval 2002…2023 (internal representation `[$date_interval = ’20020101,20031231,000000,235959']`), Korp produces the following CQP expression:

```
[((int(_.text_datefrom) = 20020101 & int(_.text_timefrom) >= 000000)
  | (int(_.text_datefrom) > 20020101 & int(_.text_datefrom) <= 20031231))
 & (int(_.text_dateto) < 20031231
    | (int(_.text_dateto) = 20031231 & int(_.text_timeto) <= 235959))]
```

I think this could be simplified to:

```
[int(_.text_datefrom) >= 20020101 & int(_.text_datefrom) <= 20031231 & int(_.text_dateto) <= 20031231]
```

For example, [this Korp frontend search](https://spraakbanken.gu.se/korp/#?cqp=%3Csentence%3E%20%5B$date_interval%20%3D%20'20020101,20031231,000000,235959'%5D&corpus=sweachum,sweacsam&search_tab=1&lang=eng&search=cqp) is now translated to [this backend query](https://ws.spraakbanken.gu.se/ws/korp/v8/query?default_context=1%20sentence&start=0&end=24&corpus=SWEACHUM%2CSWEACSAM&cqp=%3Csentence%3E%20%5B((int(_.text_datefrom)%20%3D%2020020101%20%26%20int(_.text_timefrom)%20%3E%3D%20000000)%20%7C%20(int(_.text_datefrom)%20%3E%2020020101%20%26%20int(_.text_datefrom)%20%3C%3D%2020031231))%20%26%20(int(_.text_dateto)%20%3C%2020031231%20%7C%20(int(_.text_dateto)%20%3D%2020031231%20%26%20int(_.text_timeto)%20%3C%3D%20235959))%5D&query_data=&context=&incremental=true&default_within=sentence&within=&show=sentence%2Clemma%2Cpos%2Cmsd%2Clex%2Cdephead%2Cdeprel%2Cref%2Csense%2Ccomplemgram%2Cne_ex%2Cne_name%2Cne_type%2Cne_subtype%2Ccompwf%2Cprefix%2Csuffix&show_struct=text_type%2Ctext_subject&cache=false), but it could be simplified to [this one](https://ws.spraakbanken.gu.se/ws/korp/v8/query?default_context=1%20sentence&start=0&end=24&corpus=SWEACHUM%2CSWEACSAM&cqp=%3Csentence%3E%20%5Bint(_.text_datefrom)%20%3E%3D%2020020101%20%26%20int(_.text_datefrom)%20%3C%3D%2020031231%20%26%20int(_.text_datefrom)%20%3C%3D%2020031231%20%26%20int(_.text_dateto)%20%3C%3D%2020031231%5D&query_data=&context=&incremental=true&default_within=sentence&within=&show=sentence%2Clemma%2Cpos%2Cmsd%2Clex%2Cdephead%2Cdeprel%2Cref%2Csense%2Ccomplemgram%2Cne_ex%2Cne_name%2Cne_type%2Cne_subtype%2Ccompwf%2Cprefix%2Csuffix&show_struct=text_type%2Ctext_subject&cache=false) (`cache=false` added to both to allow speed comparison).

This would be slightly faster, although the speed-up was smaller than I had expected: 5–30% in the cases I tried.

**Comment by arildm** [comment]
@janiemi This should be fixed in PR #393, could you check if it makes sense? I couldn't resist changing a few other details in the logic, I hope you don't mind.

For instance, I didn't see the point of the second condition in

```
[int(_.text_datefrom) >= 20020101 & int(_.text_datefrom) <= 20031231 & int(_.text_dateto) <= 20031231]
```

so that is now simplified further to

```
[int(_.text_datefrom) >= 20020101 & int(_.text_dateto) <= 20031231]
```

We can assume that the `datefrom` of a text is always less than or equal to its `dateto`, right?
