### ISSUE TITLE
Secondary KWIC broken in parallel mode

### ISSUE THREAD

**Issue by MartinHammarstedt** [spraakbanken/korp-frontend#41]
Opening KWIC from statistics does not work.

The `corpus` parameter to the backend is set to:
`EUROPARL-EN,ASPACSVEN-EN`
instead of the correct:
`EUROPARL-EN|EUROPARL-SV,ASPACSVEN-EN|ASPACSVEN-SV`

**Comment by majsan** [comment]
@MartinHammarstedt Changing the corpus parameter doesn't work:
https://ws.spraakbanken.gu.se/ws/korp/v8/count?group_by=word&group_by_struct=&cqp=%5Bword%20%3D%20%22dog%22%5D&corpus=EUROPARL-SV%7CEUROPARL-EN%2CASPACSVEN-SV%7CASPACSVEN-EN&incremental=true&default_within=link&within=EUROPARL-SV%3Alinken%2CASPACSVEN-SV%3Alink&split=&top=

I guess we should also change the corpora in `within`, but it shouldn't affect this bug...

**Comment by MartinHammarstedt** [comment]
I'm talking about the KWIC (`/query`) opened from the statistics view, not the statistics query itself (`/count`).

**Comment by majsan** [comment]
The problem is that *because* the corpus parameter to `/count` is without the linked corpus (whatever that means), the `/query`-call will have the wrong `corpus`-parameter, since it fetches the value from the result of `/count`.
