### ISSUE TITLE
Empty localization strings sometimes render as localization key

### ISSUE THREAD

**Issue by Traubert** [spraakbanken/korp-frontend#410]
At least in the English language version of the time graph, this happens:

![390349813-bfba5da5-1562-433b-8915-0a760ef3239c](https://github.com/user-attachments/assets/2a869bde-7a98-4be2-8b6d-87d4bcbf7851)

(Thanks @janiemi for the screenshot)

This is from [this search](https://spraakbanken.gu.se/korp/#?cqp=%5B%5D&corpus=sweachum,sweacsam&lang=eng&show_stats&result_tab=4&search=lemgram%7Cryggrad%5C.%5C.nn%5C.1).

This can be quickfixed by substituting " " for "" for the value of `non_time_before` in the English localization file. We are thinking about fixing it like [this](https://github.com/CSCfi/Kielipankki-korp-frontend/commit/a4e2b27a8db06c62d2f9ba45b0a6b60d5b0ae913). I guess in your case it might just go away when migrating to Vue, but any opinions about our fix?

**Comment by arildm** [comment]
Thanks for the bug find! Your solution looks good to me. Alternatively, we could use the [`??` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing):

```js
var value = valueForKey(key, data) ?? key;
```

While I'm editing this, I'm taking the opportunity to remove the `locPrefix`/`locSuffix` support. It looks like we haven't been using it since 2017. Let me know if you need it it back!

**Comment by janiemi** [comment]
I admit my ignorance: I didn’t know about the `??` operator, which appears to have been introduced in ES2020. Do you have guidelines as to what is the most recent ES version whose features can be used in Korp frontend code? I’ve tried to keep to ES2015 (ES6), but maybe that’s too limiting, as I think `??` and `??=` would be handy in many cases.

I don’t think we’ve ever knowingly used `locPrefix` or `locSuffix`, so it’s fine to remove them. What were the use cases for them, or what were they replaced with? I took a very quick look at the old code using them but didn’t quite get the idea.

**Comment by arildm** [comment]
I have been quite lazy about ensuring wide browser support. Thanks for bringing that up! Let's continue the discussion in:

- #411 

I also didn't quite understand the point of `locPrefix`/`locSuffix`. But I saw they were being used in a custom select component from before AngularJS was introduced to the project, so I suppose it made sense back then.
