### ISSUE TITLE
Link to Språkbankens MSD-table should be optional for all attributes

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#55]
Link to Språkbankens MSD-table should be optional for all attributes.

Currently adding the link is hard-coded in `widgets.js`.

**Comment by janiemi** [comment]
Would #195 fix this?

**Comment by majsan** [comment]
Absolutely, I will merge now.

**Comment by majsan** [comment]
Fixed in 46f001086035b452
