### ISSUE TITLE
Extended search: word at the beginning or end of structures other than sentence

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#68]
From the cog menu of a word (token) box, one could select, for example, "paragraph start", "paragraph end", "clause start" or "clause end".

Maybe the choices available could be configured individually for each corpus, or alternatively they might be extracted from the `struct_attributes` of each corpus, preferably with a possibility to override.

(This was originally reported by Jyrki.)

**Comment by majsan** [comment]
Fixed in faff967.

@janiemi #79 was needed in a project, and then this was fixed at the same time. The list of attributes that can be selected is based on the `within` parameter of corpus configuration. All attributes except those prefixed with numbers (s.a. `5 sentence`) will be used. In the future we will add an option to override this behaviour.

**Comment by janiemi** [comment]
Sounds good; thanks! I’ll test it at some point.
