### ISSUE TITLE
Move from OSM tile server for the map

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#83]
Technically we are not allowed to use OSM tiles, so we should switch to 

https://carto.com/location-data-services/basemaps/

Or some other provider that may work.

**Comment by arildm** [comment]
Is this still relevant? Why are we not allowed to use OSM tiles? I don't see any obvious problems in https://operations.osmfoundation.org/policies/tiles/

**Comment by majsan** [comment]
Me neither, they probably changed the policy.
